### ISSUE TITLE
Tracking column and dynamically process rows

### ISSUE THREAD

**Issue by harrymitchinson** [harrymitchinson/GAS.OpenBadges.me#2]
> Students (or teachers at centres) fill out a form to claim a badge. Centre’s may be given access to bulk add claims directly to the sheet. The organisation then verifies that the qualification was achieved and adds a "Y" (or something similar) to the learner's row to confirm it should be processed. Once the learner's row has been processed we should not process it again.

## Changes required
- [x] Dynamic column for issue badge.
- [x] Dynamic column for issued badge.
- [x] Track rows which have been processed during the script run and update their issued badge column.
